# https://www.wcpfc.int/wcpfc-public-domain-aggregated-catcheffort-data-download-page

all: get unzip

get:
	wget https://www.wcpfc.int/system/files/DRIFTNET_0.zip
	wget https://www.wcpfc.int/system/files/pole_and_line_2.zip
	wget https://www.wcpfc.int/system/files/purse_seine_1.zip
	wget https://www.wcpfc.int/system/files/longline_60_1.zip
	wget https://www.wcpfc.int/system/files/longline_70_1.zip
	wget https://www.wcpfc.int/system/files/longline_80_1.zip
	wget https://www.wcpfc.int/system/files/longline_90_2.zip
	wget https://www.wcpfc.int/system/files/longline_00_0.zip

unzip:
	unzip DRIFTNET_0.zip
	unzip pole_and_line_2.zip
	unzip purse_seine_1.zip
	unzip longline_60_1.zip
	unzip longline_70_1.zip
	unzip longline_80_1.zip
	unzip longline_90_2.zip
	unzip longline_00_0.zip

yearbook:
	wget https://www.wcpfc.int/system/files/YEARBOOK_2014_XLS_1.zip
